### ISSUE TITLE
Benchmark pts/himeno-1.3.0 doesn't compile with GCC 14.1.1

### ISSUE THREAD

**Issue by jirvoz** [phoronix-test-suite/phoronix-test-suite#792]
Installation of pts/himeno-1.3.0 with GCC 14.1.1 fails due to some implicit declarations mentioned below.
For compilation is used `cc (GCC) 14.1.1 20240507 (Red Hat 14.1.1-2)`
The errors look like:
```
himenobmtxpa.c:80:5: error: implicit declaration of function ‘strcpy’ [-Wimplicit-function-declaration]
   80 |     strcpy(size,argv[1]);
      |     ^~~~~~
himenobmtxpa.c:41:1: note: include ‘<string.h>’ or provide a declaration of ‘strcpy’
   40 | #include <sys/time.h>
  +++ |+#include <string.h>
   41 | 
```
or
```
himenobmtxpa.c:229:5: error: implicit declaration of function ‘exit’ [-Wimplicit-function-declaration]
  229 |     exit(6);
      |     ^~~~
himenobmtxpa.c:41:1: note: include ‘<stdlib.h>’ or provide a declaration of ‘exit’
   40 | #include <sys/time.h>
  +++ |+#include <stdlib.h>
   41 | 
```
When I add those includes to the code and compile it manually with `cc himenobmtxpa.c -O3 -mavx2 -o himenobmtxpa`, it finishes without errors.
